# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'q.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 191, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.toutiao = QtWidgets.QRadioButton(self.centralwidget)
        self.toutiao.setGeometry(QtCore.QRect(220, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(True)
        font.setWeight(75)
        self.toutiao.setFont(font)
        self.toutiao.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toutiao.setObjectName("toutiao")
        self.weibo = QtWidgets.QRadioButton(self.centralwidget)
        self.weibo.setGeometry(QtCore.QRect(220, 50, 89, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(True)
        font.setWeight(75)
        self.weibo.setFont(font)
        self.weibo.setObjectName("weibo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 90, 54, 12))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lunci = QtWidgets.QTextEdit(self.centralwidget)
        self.lunci.setGeometry(QtCore.QRect(240, 80, 41, 31))
        self.lunci.setObjectName("lunci")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(220, 150, 75, 23))
        self.ok.setObjectName("ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toutiao.setText(_translate("MainWindow", "今日头条"))
        self.weibo.setText(_translate("MainWindow", "新浪微博"))
        self.label.setText(_translate("MainWindow", "次数:"))
        self.ok.setText(_translate("MainWindow", "OK"))
